DEFAULT, RUNNING, STOPPED, YES, NO, EMPTY = 'DEFAULT', 'Running', 'Stopped', 'yes', 'no', ''
RESET, QUEUED, STARTING, CONCLUDED, RESULT, SEARCH, BEHAVIOR, SEARCHES, LOOPS = 0, 1, 2, 4, 5, 6, 7, 8, 9
RESULTS_RETURN_MAX = 15
